package alphabet;

import java.util.Random;
import java.util.Scanner;

public class MonoDriver {

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		// Read in plaintext from stdin
		/*Scanner s = new Scanner(System.in);
		String plainText = "";
		while(s.hasNextLine()){
			plainText += s.nextLine();
		}*/
		
		String cipherText = "TPZZD HAZVU ZOLRL WAWLJ RPUNH ATLHU KPANV AAPYL ZVTLH UKSVU LZVTL IFHUK IFAOL FMLAJ OLKAO LUPNN LYZPU HUKOH KWYHF LYZHU KAOLU LCLYF IVKFD HZVMM AVILK PDLUA BWAVT FYVVT DPAOH WPLJL VMJHU KSLHU KWBAP AVUAO LAHIS LAOLU PZLAK VDUPU HJOHP YIFAO LDPUK VDHUK AYPLK AVAOP URVMZ VTLAO PUNJO LLYMB SIBAP ADHYU AUVBZ LPMLS AZVSV ULZVT LPTVZ ADPZO LKPDH ZKLHK AOLZA HYZDL YLZOP UPUNH UKAOL SLHCL ZYBZA SLKPU AOLDV VKZLC LYZVT VBYUM BSHUK POLHY KHUVD SHDHF VMMDO VDOVV PUNHI VBAZV TLIVK FAOHA DHZKL HKHUK HDOPW WVDPS SHUKH KVNJY FPUNH IVBAZ VTLIV KFAOH ADHZN VPUNA VKPLH UKAOL DPUKD HZAYF PUNAV DOPZW LYZVT LAOPU NAVTL HUKPJ VBSKU ATHRL VBADO HAPAD HZHUK ZVPAT HKLAO LJVSK ZOPCL YZYBU VCLYT LAOLU HDHFV BAPUA OLDVV KZPOL HYKAO HARPU KVMHZ VBUKA OHAHN OVZAT HRLZD OLUPA DHUAZ AVALS SHIVB AZVTL AOPUN AOHAZ VUPAZ TPUKH UKJHU ATHRL PAZLS MBUKL YZAVV KHUKZ VJHUA YLZAL HZFPU PAZNY HCLHU KOHZA VNVHI VBAAO HADHF LCLYF UPNOA NYPLC PUNPN VAZVK VDUOL HYALK HUKZJ HYLKP KPKDP ZOPOH KZVTL JVTWH UFWYL AAFZV VUHZW PKLYD LUAJY HDSPU NBWTF ZOVBS KLYHU KPMSP WWLKP AVMMH UKPAS PAPUA OLJHU KSLHU KILMV YLPJV BSKIB KNLPA DHZHS SZOYP CLSLK BWPKP KUAUL LKHUF IVKFA VALSS TLAOH AAOHA DHZHU HDMBS IHKZP NUHUK DVBSK MLAJO TLZVT LIHKS BJRZV PDHZZ JHYLK HUKTV ZAZOV VRAOL JSVAO LZVMM VMTLP NVABW HUKAB YULKH YVBUK PUTFA YHJRZ AOYLL APTLZ HUKJY VZZLK TFIYL HZALC LYFAP TLHUK AOLUP APLKB WHSPA ASLSV JRVMT FOHPY DPAOH AOYLH KAVRL LWDPA JOLZH DHFIB APOHK UAUVJ VUMPK LUJLF VBKVA OHADO LUFVB CLSVZ AHOVY ZLZOV LAOHA FVBCL MVBUK PUZAL HKVMU HPSPU NPABW VCLYA OLKVV YIBAP OHKUA LCLYO LHYKH UFIVK FZHFP ADHZH UFDHF AVRLL WVMMI HKSBJ RDOLU FVBKR PSSLK HZWPK LY";
		
		Fitness fitness = new Fitness(new MonoCipher(),cipherText);
		
		Mono population = new Mono(5000,fitness);

		Random rand = new Random();
		
		MonoGeneTool geneTool = new MonoGeneTool(rand);
		
		MonoManipulator manipulator = new MonoManipulator(rand);
		
		Overlord overlord = new Overlord(population, geneTool, manipulator);
		
		//while(!overlord.isDone()){
		for (int i=0; i<1000; i++){
			//System.err.println("running a generation...");
			int ret = overlord.runGeneration();
			
			// TODO debugging
			if (ret >= 350){
				System.err.println();
			}
		}
		//}
		
	}

}
